title:              Js Blog
email:              nonehour@naver.com
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:
github_username:    jungseok-corine
facebook_username:
instagram_username:  seok2_sidae
linkedin_username:  jungseok-oh-a20173251

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
